# Generated by Django 4.2.11 on 2024-04-01 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publicar',
            fields=[
                ('id_publicação', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=200, unique=True)),
                ('subtitulo', models.TextField(max_length=100)),
                ('resumo', models.TextField()),
                ('publicado_em', models.DateField(auto_now_add=True)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(upload_to='imagens')),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria_publicação', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyber_blog.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='cyber_blog.publicar')),
            ],
            options={
                'ordering': ['-publicado_em'],
            },
        ),
    ]
