# Generated by Django 4.2.11 on 2024-04-01 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='cyber_blog.publicar'),
        ),
        migrations.AlterField(
            model_name='publicar',
            name='categoria_publicação',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='cyber_blog.categoria'),
        ),
    ]
