# Generated by Django 4.2.10 on 2024-02-23 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=200, unique=True)),
                ('autor', models.TextField()),
                ('subtitulo', models.TextField()),
                ('categoria', models.TextField()),
                ('resumo', models.TextField()),
                ('publicado_em', models.DateField(auto_now_add=True)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(upload_to='imagens')),
                ('slug', models.SlugField(blank=True, max_length=180, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='cyberblog.publicar')),
            ],
            options={
                'ordering': ['-publicado_em'],
            },
        ),
    ]
